// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52eMjLOvC34DBtHOXbw3BrirC3OpMeck',
    appId: '1:694631864901:web:8b9bbcc20d95e4cb48212c',
    messagingSenderId: '694631864901',
    projectId: 'pc-builder-comparison',
    authDomain: 'pc-builder-comparison.firebaseapp.com',
    storageBucket: 'pc-builder-comparison.firebasestorage.app',
    measurementId: 'G-C15C4H9WNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKapZKW4D_aa2snxteOwASFUdDtDC9JyI',
    appId: '1:694631864901:android:e05e05a8cf5c33c648212c',
    messagingSenderId: '694631864901',
    projectId: 'pc-builder-comparison',
    storageBucket: 'pc-builder-comparison.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuE-ntWDMUXq5wUkY50bVny8PU23_sLDs',
    appId: '1:694631864901:ios:cd6c0e3b9887b4be48212c',
    messagingSenderId: '694631864901',
    projectId: 'pc-builder-comparison',
    storageBucket: 'pc-builder-comparison.firebasestorage.app',
    iosClientId: '694631864901-7f16i4m2n1iiheqqbbjv3fnu4c72rhf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pcbuildercomparison',
  );
}
